package com.jgdsun.qms.model.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.jgdsun.qms.model.TQueueManageStatusEntity;
import com.easy.query.core.proxy.columns.types.SQLStringTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLLocalDateTimeTypeColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class TQueueManageStatusEntityProxy extends AbstractProxyEntity<TQueueManageStatusEntityProxy, TQueueManageStatusEntity> {

    private static final Class<TQueueManageStatusEntity> entityClass = TQueueManageStatusEntity.class;

    public static final TQueueManageStatusEntityProxy TABLE = createTable().createEmpty();

    public static TQueueManageStatusEntityProxy createTable() {
        return new TQueueManageStatusEntityProxy();
    }

    public TQueueManageStatusEntityProxy() {
    }

    /**
     * id
     * {@link TQueueManageStatusEntity#getId}
     */
    public SQLStringTypeColumn<TQueueManageStatusEntityProxy> id() {
        return getStringTypeColumn("id");
    }

    /**
     * 设备ID
     * {@link TQueueManageStatusEntity#getDeviceId}
     */
    public SQLStringTypeColumn<TQueueManageStatusEntityProxy> deviceId() {
        return getStringTypeColumn("deviceId");
    }

    /**
     * 添加时间
     * {@link TQueueManageStatusEntity#getAddtime}
     */
    public SQLLocalDateTimeTypeColumn<TQueueManageStatusEntityProxy> addtime() {
        return getLocalDateTimeTypeColumn("addtime");
    }

    /**
     * 设备状态 0设备异常 1上线 2下线
     * {@link TQueueManageStatusEntity#getStatus}
     */
    public SQLStringTypeColumn<TQueueManageStatusEntityProxy> status() {
        return getStringTypeColumn("status");
    }


    @Override
    public Class<TQueueManageStatusEntity> getEntityClass() {
        return entityClass;
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public TQueueManageStatusEntityProxyFetcher FETCHER = new TQueueManageStatusEntityProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class TQueueManageStatusEntityProxyFetcher extends AbstractFetcher<TQueueManageStatusEntityProxy, TQueueManageStatusEntity, TQueueManageStatusEntityProxyFetcher> {

        public TQueueManageStatusEntityProxyFetcher(TQueueManageStatusEntityProxy proxy, TQueueManageStatusEntityProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * id
         * {@link TQueueManageStatusEntity#getId}
         */
        public TQueueManageStatusEntityProxyFetcher id() {
            return add(getProxy().id());
        }

        /**
         * 设备ID
         * {@link TQueueManageStatusEntity#getDeviceId}
         */
        public TQueueManageStatusEntityProxyFetcher deviceId() {
            return add(getProxy().deviceId());
        }

        /**
         * 添加时间
         * {@link TQueueManageStatusEntity#getAddtime}
         */
        public TQueueManageStatusEntityProxyFetcher addtime() {
            return add(getProxy().addtime());
        }

        /**
         * 设备状态 0设备异常 1上线 2下线
         * {@link TQueueManageStatusEntity#getStatus}
         */
        public TQueueManageStatusEntityProxyFetcher status() {
            return add(getProxy().status());
        }


        @Override
        protected TQueueManageStatusEntityProxyFetcher createFetcher(TQueueManageStatusEntityProxy cp, AbstractFetcher<TQueueManageStatusEntityProxy, TQueueManageStatusEntity, TQueueManageStatusEntityProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new TQueueManageStatusEntityProxyFetcher(cp, this, sqlSelectExpression);
        }
    }


    public static final class Fields {
        public static final String id = "id";
        public static final String deviceId = "deviceId";
        public static final String addtime = "addtime";
        public static final String status = "status";

        private Fields() {
        }
    }
}
