package com.jgdsun.qms.model.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.jgdsun.qms.model.TQueueManageEntity;
import com.easy.query.core.proxy.columns.types.SQLStringTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLIntegerTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLLocalDateTimeTypeColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class TQueueManageEntityProxy extends AbstractProxyEntity<TQueueManageEntityProxy, TQueueManageEntity> {

    private static final Class<TQueueManageEntity> entityClass = TQueueManageEntity.class;

    public static final TQueueManageEntityProxy TABLE = createTable().createEmpty();

    public static TQueueManageEntityProxy createTable() {
        return new TQueueManageEntityProxy();
    }

    public TQueueManageEntityProxy() {
    }

    /**
     * id
     * {@link TQueueManageEntity#getId}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> id() {
        return getStringTypeColumn("id");
    }

    /**
     * 楼层ID
     * {@link TQueueManageEntity#getStoreyId}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> storeyId() {
        return getStringTypeColumn("storeyId");
    }

    /**
     * 名称
     * {@link TQueueManageEntity#getName}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> name() {
        return getStringTypeColumn("name");
    }

    /**
     * 通讯协议 ,0 modbus RTU, 1 tcpip , 2 http .....
     * {@link TQueueManageEntity#getProtocol}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> protocol() {
        return getIntegerTypeColumn("protocol");
    }

    /**
     * IP地址
     * {@link TQueueManageEntity#getIp}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> ip() {
        return getStringTypeColumn("ip");
    }

    /**
     * 设备通讯地址，通讯中的设备标识
     * {@link TQueueManageEntity#getAddress}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> address() {
        return getStringTypeColumn("address");
    }

    /**
     * 寄存器地址
     * {@link TQueueManageEntity#getRegisterAddress}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> registerAddress() {
        return getIntegerTypeColumn("registerAddress");
    }

    /**
     * 排序
     * {@link TQueueManageEntity#getSortNo}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> sortNo() {
        return getIntegerTypeColumn("sortNo");
    }

    /**
     * 效果图坐标X
     * {@link TQueueManageEntity#getPositionX}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> positionX() {
        return getIntegerTypeColumn("positionX");
    }

    /**
     * 效果图坐标Y
     * {@link TQueueManageEntity#getPositionY}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> positionY() {
        return getIntegerTypeColumn("positionY");
    }

    /**
     * 添加时间
     * {@link TQueueManageEntity#getAddtime}
     */
    public SQLLocalDateTimeTypeColumn<TQueueManageEntityProxy> addtime() {
        return getLocalDateTimeTypeColumn("addtime");
    }

    /**
     * 是否启用0不启用1启用
     * {@link TQueueManageEntity#getEnable}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> enable() {
        return getStringTypeColumn("enable");
    }

    /**
     * 设备id
     * {@link TQueueManageEntity#getEquipmentId}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> equipmentId() {
        return getStringTypeColumn("equipmentId");
    }

    /**
     * 设备序号
     * {@link TQueueManageEntity#getEquipmentSn}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> equipmentSn() {
        return getStringTypeColumn("equipmentSn");
    }

    /**
     * 状态 0下线 1后台 2运行中
     * {@link TQueueManageEntity#getStatus}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> status() {
        return getStringTypeColumn("status");
    }

    /**
     * 设备类型
     * {@link TQueueManageEntity#getTypeinfo}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> typeinfo() {
        return getStringTypeColumn("typeinfo");
    }

    /**
     * {@link TQueueManageEntity#getStat}
     */
    public SQLStringTypeColumn<TQueueManageEntityProxy> stat() {
        return getStringTypeColumn("stat");
    }

    /**
     * 效果图坐标Z 三维时单位为0.01
     * {@link TQueueManageEntity#getPositionZ}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> positionZ() {
        return getIntegerTypeColumn("positionZ");
    }

    /**
     * x轴旋转 单位为0.01
     * {@link TQueueManageEntity#getRotationX}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> rotationX() {
        return getIntegerTypeColumn("rotationX");
    }

    /**
     * Y轴旋转 单位为0.01
     * {@link TQueueManageEntity#getRotationY}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> rotationY() {
        return getIntegerTypeColumn("rotationY");
    }

    /**
     * Z轴旋转 单位为0.01
     * {@link TQueueManageEntity#getRotationZ}
     */
    public SQLIntegerTypeColumn<TQueueManageEntityProxy> rotationZ() {
        return getIntegerTypeColumn("rotationZ");
    }


    @Override
    public Class<TQueueManageEntity> getEntityClass() {
        return entityClass;
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public TQueueManageEntityProxyFetcher FETCHER = new TQueueManageEntityProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class TQueueManageEntityProxyFetcher extends AbstractFetcher<TQueueManageEntityProxy, TQueueManageEntity, TQueueManageEntityProxyFetcher> {

        public TQueueManageEntityProxyFetcher(TQueueManageEntityProxy proxy, TQueueManageEntityProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * id
         * {@link TQueueManageEntity#getId}
         */
        public TQueueManageEntityProxyFetcher id() {
            return add(getProxy().id());
        }

        /**
         * 楼层ID
         * {@link TQueueManageEntity#getStoreyId}
         */
        public TQueueManageEntityProxyFetcher storeyId() {
            return add(getProxy().storeyId());
        }

        /**
         * 名称
         * {@link TQueueManageEntity#getName}
         */
        public TQueueManageEntityProxyFetcher name() {
            return add(getProxy().name());
        }

        /**
         * 通讯协议 ,0 modbus RTU, 1 tcpip , 2 http .....
         * {@link TQueueManageEntity#getProtocol}
         */
        public TQueueManageEntityProxyFetcher protocol() {
            return add(getProxy().protocol());
        }

        /**
         * IP地址
         * {@link TQueueManageEntity#getIp}
         */
        public TQueueManageEntityProxyFetcher ip() {
            return add(getProxy().ip());
        }

        /**
         * 设备通讯地址，通讯中的设备标识
         * {@link TQueueManageEntity#getAddress}
         */
        public TQueueManageEntityProxyFetcher address() {
            return add(getProxy().address());
        }

        /**
         * 寄存器地址
         * {@link TQueueManageEntity#getRegisterAddress}
         */
        public TQueueManageEntityProxyFetcher registerAddress() {
            return add(getProxy().registerAddress());
        }

        /**
         * 排序
         * {@link TQueueManageEntity#getSortNo}
         */
        public TQueueManageEntityProxyFetcher sortNo() {
            return add(getProxy().sortNo());
        }

        /**
         * 效果图坐标X
         * {@link TQueueManageEntity#getPositionX}
         */
        public TQueueManageEntityProxyFetcher positionX() {
            return add(getProxy().positionX());
        }

        /**
         * 效果图坐标Y
         * {@link TQueueManageEntity#getPositionY}
         */
        public TQueueManageEntityProxyFetcher positionY() {
            return add(getProxy().positionY());
        }

        /**
         * 添加时间
         * {@link TQueueManageEntity#getAddtime}
         */
        public TQueueManageEntityProxyFetcher addtime() {
            return add(getProxy().addtime());
        }

        /**
         * 是否启用0不启用1启用
         * {@link TQueueManageEntity#getEnable}
         */
        public TQueueManageEntityProxyFetcher enable() {
            return add(getProxy().enable());
        }

        /**
         * 设备id
         * {@link TQueueManageEntity#getEquipmentId}
         */
        public TQueueManageEntityProxyFetcher equipmentId() {
            return add(getProxy().equipmentId());
        }

        /**
         * 设备序号
         * {@link TQueueManageEntity#getEquipmentSn}
         */
        public TQueueManageEntityProxyFetcher equipmentSn() {
            return add(getProxy().equipmentSn());
        }

        /**
         * 状态 0下线 1后台 2运行中
         * {@link TQueueManageEntity#getStatus}
         */
        public TQueueManageEntityProxyFetcher status() {
            return add(getProxy().status());
        }

        /**
         * 设备类型
         * {@link TQueueManageEntity#getTypeinfo}
         */
        public TQueueManageEntityProxyFetcher typeinfo() {
            return add(getProxy().typeinfo());
        }

        /**
         * {@link TQueueManageEntity#getStat}
         */
        public TQueueManageEntityProxyFetcher stat() {
            return add(getProxy().stat());
        }

        /**
         * 效果图坐标Z 三维时单位为0.01
         * {@link TQueueManageEntity#getPositionZ}
         */
        public TQueueManageEntityProxyFetcher positionZ() {
            return add(getProxy().positionZ());
        }

        /**
         * x轴旋转 单位为0.01
         * {@link TQueueManageEntity#getRotationX}
         */
        public TQueueManageEntityProxyFetcher rotationX() {
            return add(getProxy().rotationX());
        }

        /**
         * Y轴旋转 单位为0.01
         * {@link TQueueManageEntity#getRotationY}
         */
        public TQueueManageEntityProxyFetcher rotationY() {
            return add(getProxy().rotationY());
        }

        /**
         * Z轴旋转 单位为0.01
         * {@link TQueueManageEntity#getRotationZ}
         */
        public TQueueManageEntityProxyFetcher rotationZ() {
            return add(getProxy().rotationZ());
        }


        @Override
        protected TQueueManageEntityProxyFetcher createFetcher(TQueueManageEntityProxy cp, AbstractFetcher<TQueueManageEntityProxy, TQueueManageEntity, TQueueManageEntityProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new TQueueManageEntityProxyFetcher(cp, this, sqlSelectExpression);
        }
    }


    public static final class Fields {
        public static final String id = "id";
        public static final String storeyId = "storeyId";
        public static final String name = "name";
        public static final String protocol = "protocol";
        public static final String ip = "ip";
        public static final String address = "address";
        public static final String registerAddress = "registerAddress";
        public static final String sortNo = "sortNo";
        public static final String positionX = "positionX";
        public static final String positionY = "positionY";
        public static final String addtime = "addtime";
        public static final String enable = "enable";
        public static final String equipmentId = "equipmentId";
        public static final String equipmentSn = "equipmentSn";
        public static final String status = "status";
        public static final String typeinfo = "typeinfo";
        public static final String stat = "stat";
        public static final String positionZ = "positionZ";
        public static final String rotationX = "rotationX";
        public static final String rotationY = "rotationY";
        public static final String rotationZ = "rotationZ";

        private Fields() {
        }
    }
}
